# Generated by Django 5.1 on 2025-10-01 06:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('TRY', '₺'), ('USD', '$')], default='TRY', max_length=3, verbose_name='Para Birimi'),
        ),
        migrations.AddField(
            model_name='item',
            name='group',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grup'),
        ),
        migrations.AddField(
            model_name='item',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mevsim'),
        ),
        migrations.CreateModel(
            name='Siparis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='siparis_no', unique=True)),
                ('siparis_no', models.CharField(max_length=50, unique=True, verbose_name='Sipariş No')),
                ('siparis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Sipariş Tarihi')),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('URUN_GELDI', 'Ürün Geldi'), ('KARGODA', 'Kargoda'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('IPTAL', 'İptal')], default='BEKLEMEDE', max_length=20, verbose_name='Durum')),
                ('son_dur', models.CharField(blank=True, choices=[('YF', 'Y.F'), ('!', '!'), ('', '')], max_length=10, null=True, verbose_name='Son Dur')),
                ('ambar', models.CharField(choices=[('SATIS', 'Satış'), ('STOK', 'Stok'), ('BEKLEMEDE', 'Beklemede')], default='BEKLEMEDE', max_length=20, verbose_name='Ambar')),
                ('aciklama1', models.TextField(blank=True, null=True, verbose_name='Açıklama 1')),
                ('tura_durum', models.CharField(choices=[('FT_ISLENDI', 'Fatura İşlendi'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLEMEDE', max_length=20, verbose_name='Tura Durum')),
                ('odeme', models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('KART', 'Kredi Kartı'), ('GARANTI_KK', 'Garanti K.K'), ('HAVALE', 'Havale'), ('CEK', 'Çek')], max_length=20, null=True, verbose_name='Ödeme')),
                ('sms_gonderildi', models.BooleanField(default=False, verbose_name='SMS Gönderildi')),
                ('toplam_tutar', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Tutar')),
                ('cari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.customer', verbose_name='Cari')),
            ],
            options={
                'verbose_name': 'Sipariş',
                'verbose_name_plural': 'Siparişler',
                'ordering': ['-siparis_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SiparisKalemi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adet', models.IntegerField(default=1, verbose_name='Adet')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Toplam Fiyat')),
                ('siparis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='store.siparis', verbose_name='Sipariş')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.item', verbose_name='Ürün')),
            ],
            options={
                'verbose_name': 'Sipariş Kalemi',
                'verbose_name_plural': 'Sipariş Kalemleri',
            },
        ),
    ]
