# Generated by Django 5.1.4 on 2025-10-01 10:06

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('store', '0002_item_brand_item_currency_item_group_item_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastikEnvanteri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cari', models.CharField(max_length=100, verbose_name='Cari (Firma)')),
                ('urun', models.CharField(max_length=200, verbose_name='Ürün (Lastik Marka Model)')),
                ('marka', models.CharField(max_length=100, verbose_name='Marka')),
                ('grup', models.CharField(choices=[('BINEK', 'Binek'), ('TICARI', 'Ticari'), ('AKU', 'Akü')], max_length=20, verbose_name='Grup')),
                ('mevsim', models.CharField(choices=[('YAZ', 'Yaz'), ('KIS', 'Kış'), ('4MEVSIM', '4 Mevsim')], max_length=20, verbose_name='Mevsim')),
                ('adet', models.IntegerField(default=1, verbose_name='Adet')),
                ('birim_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat')),
                ('toplam_fiyat', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Fiyat')),
                ('durum', models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('URUN_GELDI', 'Ürün Geldi'), ('YOLDA', 'Yolda'), ('TESLIM_EDILDI', 'Teslim Edildi')], default='BEKLEMEDE', max_length=20, verbose_name='Durum')),
                ('son_dur', models.CharField(blank=True, choices=[('YF', 'Y.F'), ('!', '!'), ('', '')], max_length=10, null=True, verbose_name='Son Dur')),
                ('ambar', models.CharField(choices=[('SATIS', 'Satış'), ('STOK', 'Stok')], default='STOK', max_length=20, verbose_name='Ambar')),
                ('aciklama1', models.TextField(blank=True, null=True, verbose_name='Açıklama 1')),
                ('tura_durum', models.CharField(choices=[('FT_ISLENDI', 'Fatura İşlendi'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLEMEDE', max_length=20, verbose_name='Tura Durum')),
                ('odeme', models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('KART', 'Kredi Kartı'), ('GARANTI_KK', 'Garanti K.K'), ('HAVALE', 'Havale'), ('CEK', 'Çek')], max_length=20, null=True, verbose_name='Ödeme')),
                ('sms_gonderildi', models.BooleanField(default=False, verbose_name='SMS Gönderildi')),
                ('olusturma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturma Tarihi')),
                ('guncelleme_tarihi', models.DateTimeField(auto_now=True, verbose_name='Güncelleme Tarihi')),
            ],
            options={
                'verbose_name': 'Lastik Envanteri',
                'verbose_name_plural': 'Lastik Envanteri',
                'ordering': ['-olusturma_tarihi'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Kategori Adı'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='customer_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Müşteri Adı'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='date',
            field=models.DateTimeField(verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='is_delivered',
            field=models.BooleanField(default=False, verbose_name='Teslim Edildi'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.item', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Konum'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='item',
            name='expiring_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Kullanma Tarihi'),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(blank=True, choices=[('BINEK', 'Binek'), ('TICARI', 'Ticari'), ('AKU', 'Akü')], max_length=50, null=True, verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Ürün Adı'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Adet'),
        ),
        migrations.AlterField(
            model_name='item',
            name='season',
            field=models.CharField(blank=True, choices=[('YAZ', 'Yaz'), ('KIS', 'Kış'), ('4MEVSIM', '4 Mevsim')], max_length=20, null=True, verbose_name='Mevsim'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.vendor', verbose_name='Tedarikçi'),
        ),
    ]
