# Generated by Django 5.1.4 on 2025-10-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_lastikenvanteri_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastikenvanteri',
            name='lastik_kodu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Lastik Kodu'),
        ),
    ]
