# Generated by Django 5.1.4 on 2025-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_lastikenvanteri_lastik_kodu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastikenvanteri',
            name='tura_durum',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='tura_durum',
        ),
        migrations.AddField(
            model_name='lastikenvanteri',
            name='fatura_durum',
            field=models.CharField(choices=[('FT_ISLENDI', 'Fatura İşlendi'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLEMEDE', max_length=20, verbose_name='Fatura Durum'),
        ),
        migrations.AddField(
            model_name='siparis',
            name='fatura_durum',
            field=models.CharField(choices=[('FT_ISLENDI', 'Fatura İşlendi'), ('BEKLEMEDE', 'Beklemede'), ('TAMAMLANDI', 'Tamamlandı')], default='BEKLEMEDE', max_length=20, verbose_name='Fatura Durum'),
        ),
    ]
