# Generated by Django 5.1.4 on 2025-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_rename_tura_durum_to_fatura_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='durum',
            field=models.CharField(choices=[('BEKLEMEDE', 'Beklemede'), ('URUN_GELDI', 'Ürün Geldi'), ('YOLDA', 'Yolda'), ('TESLIM_EDILDI', 'Teslim Edildi')], default='YOLDA', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('YOLDA', 'Yolda'), ('ISLEM_DEVAM_EDIYOR', 'İşlem Devam Ediyor'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('KONTROL_EDILDI', 'Kontrol Edildi'), ('BEKLEMEDE', 'Beklemede'), ('URUN_GELDI', 'Ürün Geldi'), ('KARGODA', 'Kargoda'), ('IPTAL', 'İptal')], default='BEKLEMEDE', max_length=20, verbose_name='Durum'),
        ),
    ]
