# Generated by Django 5.1.4 on 2025-10-02 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_lastikenvanteri_durum_alter_siparis_durum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastikenvanteri',
            name='fatura_durum',
        ),
        migrations.RemoveField(
            model_name='lastikenvanteri',
            name='son_dur',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='fatura_durum',
        ),
        migrations.RemoveField(
            model_name='siparis',
            name='son_dur',
        ),
    ]
