# Generated by Django 5.1.4 on 2025-10-02 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_lastikenvanteri_lastik_kodu_alter_item_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.CharField(blank=True, choices=[('BINEK', 'Binek'), ('TICARI', 'Ticari'), ('AKU', 'Akü')], max_length=50, null=True, verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='item',
            name='season',
            field=models.CharField(blank=True, choices=[('YAZ', 'Yaz'), ('KIS', 'Kış'), ('4MEVSIM', '4 Mevsim')], max_length=20, null=True, verbose_name='Mevsim'),
        ),
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='ambar',
            field=models.CharField(choices=[('SATIS', 'Satış'), ('STOK', 'Stok')], default='STOK', max_length=20, verbose_name='Ambar'),
        ),
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='durum',
            field=models.CharField(choices=[('YOLDA', 'Yolda'), ('ISLEM_DEVAM_EDIYOR', 'İşlem Devam Ediyor'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('KONTROL_EDILDI', 'Kontrol Edildi'), ('BEKLEMEDE', 'Beklemede'), ('URUN_GELDI', 'Ürün Geldi'), ('KARGODA', 'Kargoda'), ('IPTAL', 'İptal')], default='YOLDA', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='grup',
            field=models.CharField(choices=[('BINEK', 'Binek'), ('TICARI', 'Ticari'), ('AKU', 'Akü')], max_length=20, verbose_name='Grup'),
        ),
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='mevsim',
            field=models.CharField(choices=[('YAZ', 'Yaz'), ('KIS', 'Kış'), ('4MEVSIM', '4 Mevsim')], max_length=20, verbose_name='Mevsim'),
        ),
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='odeme',
            field=models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('KART', 'Kredi Kartı'), ('GARANTI_KK', 'Garanti K.K'), ('HAVALE', 'Havale'), ('CEK', 'Çek')], max_length=20, null=True, verbose_name='Ödeme'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='ambar',
            field=models.CharField(choices=[('SATIS', 'Satış'), ('STOK', 'Stok'), ('BEKLEMEDE', 'Beklemede')], default='BEKLEMEDE', max_length=20, verbose_name='Ambar'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='durum',
            field=models.CharField(choices=[('YOLDA', 'Yolda'), ('ISLEM_DEVAM_EDIYOR', 'İşlem Devam Ediyor'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('KONTROL_EDILDI', 'Kontrol Edildi'), ('BEKLEMEDE', 'Beklemede'), ('URUN_GELDI', 'Ürün Geldi'), ('KARGODA', 'Kargoda'), ('IPTAL', 'İptal')], default='BEKLEMEDE', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='siparis',
            name='odeme',
            field=models.CharField(blank=True, choices=[('NAKIT', 'Nakit'), ('KART', 'Kredi Kartı'), ('GARANTI_KK', 'Garanti K.K'), ('HAVALE', 'Havale'), ('CEK', 'Çek')], max_length=20, null=True, verbose_name='Ödeme'),
        ),
    ]
