# Generated by Django 5.1.4 on 2025-10-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_item_group_alter_item_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='durum',
            field=models.CharField(choices=[('YOLDA', 'Yolda'), ('ISLEM_DEVAM_EDIYOR', 'İşlem Devam Ediyor'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('KONTROL_EDILDI', 'Kontrol Edildi')], default='YOLDA', max_length=20, verbose_name='Durum'),
        ),
    ]
