# Generated by Django 5.1.4 on 2025-10-03 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_lastikenvanteri_durum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='odeme',
            field=models.CharField(blank=True, choices=[('KART', 'Kredi Kartı'), ('HAVALE', 'Havale')], max_length=20, null=True, verbose_name='Ödeme'),
        ),
    ]
