# Generated by Django 5.1.4 on 2025-10-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_lastikenvanteri_odeme'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastikenvanteri',
            name='one_cikar',
            field=models.BooleanField(default=False, verbose_name='Öne Çıkar'),
        ),
    ]
