# Generated by Django 5.1.4 on 2025-10-07 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_company_customer_company_profile_company_and_more'),
        ('store', '0014_lastikenvanteri_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sipariskalemi',
            name='siparis',
        ),
        migrations.RemoveField(
            model_name='sipariskalemi',
            name='urun',
        ),
        migrations.AddField(
            model_name='category',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='item',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Şirket'),
        ),
        migrations.AddField(
            model_name='lastikenvanteri',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Şirket'),
        ),
        migrations.DeleteModel(
            name='Siparis',
        ),
        migrations.DeleteModel(
            name='SiparisKalemi',
        ),
    ]
