# Generated by Django 5.1.4 on 2025-10-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_add_user_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='company',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='company',
        ),
        migrations.RemoveField(
            model_name='item',
            name='company',
        ),
        migrations.RemoveField(
            model_name='lastikenvanteri',
            name='company',
        ),
    ]
