# Generated by Django 5.1.4 on 2025-10-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_lastikenvanteri_created_lastikenvanteri_is_removed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='durum',
            field=models.CharField(choices=[('YOLDA', 'Yolda'), ('ISLEM_DEVAM_EDIYOR', 'İşlem Devam Ediyor'), ('TESLIM_EDILDI', 'Teslim Edildi'), ('KONTROL_EDILDI', 'Kontrol Edildi'), ('IPTAL_EDILDI', 'İptal Edildi')], default='YOLDA', max_length=20, verbose_name='Durum'),
        ),
    ]
