# Generated by Django 5.1.4 on 2025-10-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_lastikenvanteri_durum'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastikenvanteri',
            name='iptal_sebebi',
            field=models.TextField(blank=True, null=True, verbose_name='İptal Sebebi'),
        ),
    ]
