# Generated by Django 5.1.4 on 2025-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_lastikenvanteri_iptal_sebebi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='odeme',
            field=models.CharField(blank=True, choices=[('KART', 'Kredi Kartı'), ('HAVALE', 'Havale'), ('CARI_HESAP', 'Cari Hesap')], max_length=20, null=True, verbose_name='Ödeme'),
        ),
    ]
