# Generated by Django 5.1.4 on 2025-10-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_lastikenvanteri_odeme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastikenvanteri',
            name='grup',
            field=models.CharField(choices=[('BINEK', 'Binek'), ('TICARI', 'Ticari'), ('AKU', 'Akü'), ('JANT', 'Jant')], max_length=20, verbose_name='Grup'),
        ),
    ]
