# Generated by Django 5.1.4 on 2025-10-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_user_fields'),
        ('store', '0017_remove_category_company_remove_delivery_company_and_more'),
        ('transactions', '0007_remove_purchase_company_remove_sale_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='company',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='company',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
