# Generated by Django 5.1.4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_purchase_company_sale_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Kullanıcı'),
        ),
        migrations.AddField(
            model_name='sale',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Kullanıcı'),
        ),
    ]
