# Generated by Django 5.1.4 on 2025-10-07 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_add_user_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='company',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='company',
        ),
    ]
