# Generated by Django 5.1.4 on 2025-10-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_purchase_created_purchase_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='aciklama',
            field=models.TextField(blank=True, help_text='Ek açıklamalar', max_length=500, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='dot',
            field=models.CharField(blank=True, help_text='Lastik üretim yılı (örn: 2025)', max_length=4, null=True, verbose_name='DOT'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='durum',
            field=models.CharField(choices=[('COK_IYI', 'Çok İyi'), ('IYI', 'İyi'), ('ORTA', 'Orta'), ('KOTU', 'Kötü')], default='IYI', help_text='Lastik durumu', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='giris_tarihi',
            field=models.DateTimeField(blank=True, help_text='Lastiğin depoya giriş tarihi', null=True, verbose_name='Giriş Tarihi'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='marka',
            field=models.CharField(blank=True, help_text='Lastik markası', max_length=100, null=True, verbose_name='Marka'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='mevsim',
            field=models.CharField(blank=True, choices=[('YAZ', 'Yaz'), ('KIS', 'Kış'), ('SONBAHAR', 'Sonbahar'), ('4MEVSIM', '4 Mevsim')], help_text='Lastik mevsimi', max_length=20, null=True, verbose_name='Mevsim'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='urun',
            field=models.CharField(blank=True, help_text='Lastik marka ve modeli', max_length=200, null=True, verbose_name='Ürün (Lastik Marka Model)'),
        ),
    ]
