# Generated by Django 5.1.4 on 2025-10-11 07:23

import django.db.models.deletion
import django_extensions.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customer_created_customer_is_removed_and_more'),
        ('store', '0022_alter_lastikenvanteri_grup'),
        ('transactions', '0009_purchase_aciklama_purchase_dot_purchase_durum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.item'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='mevsim',
            field=models.CharField(blank=True, choices=[('YAZ', 'Yaz'), ('KIS', 'Kış'), ('4MEVSIM', '4 Mevsim')], help_text='Lastik mevsimi', max_length=20, null=True, verbose_name='Mevsim'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='urun', unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='accounts.vendor'),
        ),
    ]
