# Generated by Django 5.1.4 on 2025-10-11 13:30

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0010_alter_purchase_item_alter_purchase_mevsim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='urun'),
        ),
    ]
